default_mode: "safe"
default_strategy: "llm"
fallback_to_regex: true

llm:
  endpoint: "http://127.0.0.1:1234/v1/chat/completions"
  model: "google/gemma-3-1b"
  timeout_s: 20

scrub:
  placeholder_style: "angle"  # "angle" -> <NAME>, "bracket" -> [NAME]

report:
  enable: true
  path: "out/PII_REPORT.json"