providers:
  openai:
    api_key_env: "OPENAI_API_KEY"
    base_url: "https://api.openai.com/v1"
    models:
      - "gpt-4o-mini"
      - "gpt-4o"
      - "gpt-3.5-turbo"
  
  local:
    base_url: "http://localhost:1234/v1"
    api_key: "not-needed"
    models:
      - "local-model"
  
  ollama:
    base_url: "http://localhost:11434/v1"
    api_key: "not-needed"
    models:
      - "llama3"
      - "mistral"
      - "codellama"